# Generated by Django 4.1.7 on 2023-03-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_name', models.CharField(max_length=25)),
                ('prd_price', models.IntegerField()),
                ('prd_qnty', models.IntegerField()),
                ('prd_desc', models.CharField(max_length=25)),
                ('prd_mfg_date', models.DateField()),
            ],
        ),
    ]
